SELF-CONTAINED BINARIES AND LIBRARIES BETA VERSION

diff --git a/cloonix/cloonix_ice b/cloonix/cloonix_ice
--- a/cloonix/cloonix_ice
+++ b/cloonix/cloonix_ice
@@ -1,33 +1,25 @@
 #!/bin/bash
 set -e
 
-if (( ${#} < 1 )); then
-  echo
-  echo "$0 <net> <vm_name>"
-  echo
-  echo net:
-  echo $LIST
-  echo
-  exit 1
-fi
-
-if [ -z $CLOONIX_CONFIG ]; then
-  CLOONIX_CONFIG=/usr/local/bin/cloonix/cloonix_config
-fi
-
+CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
 if [ ! -f $CLOONIX_CONFIG ]; then
   echo "ERROR: $CLOONIX_CONFIG not found"
   exit 1
 fi
-CLOONIX_TREE=$(cat $CLOONIX_CONFIG |grep  CLOONIX_TREE | awk -F = '{print $2}')
-
-if [ ! -d ${CLOONIX_TREE} ]; then
-  echo "ERROR: ${CLOONIX_TREE} not found"
+BIN_ICE="/usr/libexec/cloonix/client/cloonix-spicy"
+if [ ! -x $BIN_ICE ]; then
+  echo "ERROR: $BIN_ICE not found"
   exit 1
 fi
-
 LIST=$(cat $CLOONIX_CONFIG |grep CLOONIX_NET: | awk '{print $2}')
-
+if (( ${#} < 1 )); then
+  echo
+  echo "$0 <net> <vm_name>"
+  echo
+  echo  cloonix_name needed as parameter.
+  echo $LIST
+  exit 1
+fi
 cloonix_name=$1
 found=no
 for i in $LIST ; do
@@ -42,6 +34,7 @@ if [ "$found" == "no" ]; then
   exit 1
 fi
 
+
 LINE_CLOONIX_CONFIG=$(cat $CLOONIX_CONFIG)
 LINE_CLOONIX_CONFIG=$(echo $LINE_CLOONIX_CONFIG)
 cloonix_info="${LINE_CLOONIX_CONFIG##*CLOONIX_NET: $cloonix_name \{}"
@@ -52,17 +45,23 @@ port=$(echo $cloonix_info |awk '{print $4}')
 passwd=$(echo $cloonix_info |awk '{print $6}')
 
 
-DIST_CLOONIX_WORK=$(cloonix_cli $cloonix_name dcf |grep  CLOONIX_WORK | awk -F = '{print $2}')
-
 ID=$(cloonix_cli $cloonix_name dmp |grep "^$2 vm_id:" | awk '{print $3}')
 if [ -z $ID ]; then
   echo Bad param: $2
   exit 1
 fi
 
-export LD_LIBRARY_PATH=${CLOONIX_TREE}/common/spice_lib
+export FONTCONFIG_FILE="/usr/libexec/cloonix/common/etc/fonts/fonts.conf"
+export XDG_CONFIG_HOME="/usr/libexec/cloonix/common/share"
+export XDG_DATA_HOME="/usr/libexec/cloonix/common/share"
+export XDG_RUNTIME_DIR="/var/lib/cloonix/${cloonix_name}"
+export QT_PLUGIN_PATH="/usr/libexec/cloonix/common/lib/qt6/plugins"
+export QT_X11_NO_MITSHM="1"
+export QT_XCB_NO_MITSHM="1"
+export GTK_IM_MODULE_FILE="/usr/libexec/cloonix/common/lib/gtk-3.0/3.0.0/immodules.cache"
+export GDK_PIXBUF_MODULE_FILE="/usr/libexec/cloonix/common/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
+export GST_PLUGIN_SYSTEM_PATH="/usr/libexec/cloonix/common/lib/gstreamer-1.0"
+export NO_AT_BRIDGE="1"
 
-BIN_ICE=${CLOONIX_TREE}/client/spice/spicy
-
-${BIN_ICE} --title=${1}/${2} -d ${ip}:${port} -c ${DIST_CLOONIX_WORK}/vm/vm${ID}/spice_sock -w ${passwd}
+${BIN_ICE} --title=${1}/${2} -d ${ip}:${port} -c /var/lib/cloonix/${cloonix_name}/vm/vm${ID}/spice_sock -w ${passwd} &
 
diff --git a/cloonix/cloonix_net b/cloonix/cloonix_net
--- a/cloonix/cloonix_net
+++ b/cloonix/cloonix_net
@@ -1,22 +1,35 @@
 #!/bin/bash
 set -e
-if [ -z $CLOONIX_CONFIG ]; then
-  CLOONIX_CONFIG=/usr/local/bin/cloonix/cloonix_config
-fi
 
+CLOONIX_CONFIG="/usr/libexec/cloonix/common/etc/cloonix.cfg"
 if [ ! -f $CLOONIX_CONFIG ]; then
   echo "ERROR: $CLOONIX_CONFIG not found"
   exit 1
 fi
-CLOONIX_TREE=$(cat $CLOONIX_CONFIG |grep  CLOONIX_TREE | awk -F = '{print $2}')
-
-if [ ! -d ${CLOONIX_TREE} ]; then
-  echo "ERROR: ${CLOONIX_TREE} not found"
+SWITCH_BIN="/usr/libexec/cloonix/server/cloonix-main-server"
+if [ ! -x $SWITCH_BIN ]; then
+  echo "ERROR: $SWITCH_BIN not found"
   exit 1
 fi
+LIST=$(cat $CLOONIX_CONFIG |grep CLOONIX_NET: | awk '{print $2}')
+if (( ${#} < 1 )); then
+  echo  cloonix_name needed as parameter.
+  echo $LIST
+  exit 1
+fi
+cloonix_name=$1
 
-SWITCH_BIN=${CLOONIX_TREE}/server/uml_cloonix_switch/uml_cloonix_switch
-
+export FONTCONFIG_FILE="/usr/libexec/cloonix/common/etc/fonts/fonts.conf"
+export XDG_CONFIG_HOME="/usr/libexec/cloonix/common/share"
+export XDG_DATA_HOME="/usr/libexec/cloonix/common/share"
+export XDG_RUNTIME_DIR="/var/lib/cloonix/${cloonix_name}"
+export QT_PLUGIN_PATH="/usr/libexec/cloonix/common/lib/qt6/plugins"
+export QT_X11_NO_MITSHM="1"
+export QT_XCB_NO_MITSHM="1"
+export GTK_IM_MODULE_FILE="/usr/libexec/cloonix/common/lib/gtk-3.0/3.0.0/immodules.cache"
+export GDK_PIXBUF_MODULE_FILE="/usr/libexec/cloonix/common/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
+export GST_PLUGIN_SYSTEM_PATH="/usr/libexec/cloonix/common/lib/gstreamer-1.0"
+export NO_AT_BRIDGE="1"
 
 ${SWITCH_BIN} $CLOONIX_CONFIG "$@"
 ##############################################################################
